### ISSUE TITLE
Html occlude blending prop creates strange artifact 

### ISSUE THREAD

**Issue by MaximeHeckel** [pmndrs/drei#1219]
- "react": "18.2.0",
- "react-dom": "18.2.0",
- "@react-three/drei": "^9.51.15",
- "@react-three/fiber": "^8.9.1",
- "three": "^0.146.0"

### Problem description:

Played a bit with the `occlude="blending"` prop of the `Html` on a simple scene, but it renders a "white" rectangle/artifact around the HTML which interfere with the scene. Not sure if this is expected or not, or if there are existing workarounds

<img width="639" alt="Screenshot 2023-01-07 at 11 24 34 AM" src="https://user-images.githubusercontent.com/2974412/211160590-83a79b6b-f85d-43b4-973f-dcadbe6e2784.png">

<img width="1356" alt="Screenshot 2023-01-07 at 11 24 50 AM" src="https://user-images.githubusercontent.com/2974412/211160604-a1109bb1-a529-483d-a69a-5e56f38ab250.png">

### Relevant code:

See repro here: https://codesandbox.io/s/compassionate-hill-fe98w2?file=/src/App.js:325-331

Notice the white square around the HTML that interferes with the background color of the scene

**Comment by FarazzShaikh** [comment]
This is a limitation that should be documented in the readme. 

The blending cuts out the canvas using a "bakcing geo" and its alpha. By default the blending uses a plane as the backing geo (that auto sizes to the inner HTML ) making it so that only rectangle elements will look right. 

You can overcome this for simple things like rounded corners by using the `geometry` prop and providing your own backing geo that matches your HTML but things like text or things with alpha will never looks right. Youre better off using `<Text />` for text.

**Comment by FarazzShaikh** [comment]
Added to readme, closing as unplanned

**Comment by MaximeHeckel** [comment]
Thank you @FarazzShaikh makes sense! Will look for a workaround, for my use case, using <Text/> won't be possible sadly
