### ISSUE TITLE
RFC: Moving drei into the r3f monorepo

### ISSUE THREAD

**Issue by itsdouges** [pmndrs/drei#1224]
Hey folks! With the eslint plugin being added to the r3f monorepo soon, and talks about it making sense for the babel plugin to live there too, it got me thinking drei would be another logical choice for bringing into the monorepo.

I see a few value propositions here:

- easier time keeping the ecosystem up-to-date
- major version upgrades will be easier
- bugs and testing can be exposed faster with less effort

It isn't without drawbacks though, some obvious some maybe not as much.

- long running branches become riskier as there are more modules in play, think direct work on the core lib and drei modules use the changing features. Backwards compat expand/collapse releases would be more important here to prevent huge blow out pull requests.
- issues/discussions would potentially flood r3f issues if we aren't careful, would need to categorise (hopefully a gh tool exists to automate this based on keywords)

I also think that if we're interested in moving it into the monorepo perhaps it might make sense to rename the package to @react-three/std? Similar to Deno, Ruby, and such I kind of see drei evolving to be collection of high quality supported modules, if it's named with std it's more familiar to the wider ecosystem I feel.

Would love people's thoughts! Please chime in.

**Comment by drcmda** [comment]
i think it would make a mess through with github rights and cause maintenance hickups, basically the same way it completely stalls threejs. three moves so slow because the 2-3 core devs can't/won't/don't review that much code. also the issues, i'm seeing black if i imagine bugs for drei will be mixed with core.

i'm fine with lots of people managing drei and having stake, there should be more devs managing std-lib even. not so much with fiber, it should be within a smaller group of devs that know it really well.

**Comment by joshuaellis** [comment]
We had discussed this a few times before now and the biggest issue for me is the pace at which this library moves, one of the biggest benefits of this lib is the semantic commits release system which means no one has to do a manual release something which we'd then find happening a lot in the `react-three` monorepo which is then susceptible to accidental releases & then we have to give publishing rights to X devs for X packages which imo is a security risk.

I do understand the benefits, but for me, these downsides outweight them still.

**Comment by joshuaellis** [comment]
> If the r3f repo isn't set up with the change sets gh app we should do that asap as you don't need permissions other than merging a version pull request.

It's not no, I set it up in `react-spring` but it's not tried to do a release for me even if there are changesets, maybe I set it up wrong?

**Comment by itsdouges** [comment]
> > If the r3f repo isn't set up with the change sets gh app we should do that asap as you don't need permissions other than merging a version pull request.
> 
> 
> 
> It's not no, I set it up in `react-spring` but it's not tried to do a release for me even if there are changesets, maybe I set it up wrong?

Possibly! I can take a look at fixing it soon. I've set it up previously.

**Comment by drcmda** [comment]
> Paul you make a good point about the issues and reviewing. How does drei manage reviewing today? That would definitely slow things down, a scenario I can imagine is a code change happens, drei code blocks, release blocks.

not sure if that's the best, but imo it somewhat works. pmndrs gives stake to devs that are using the tools or have self interest in maintaining them. a contributor that shows responsibility is generally invited and trusted to do right. that way core maintainers can have a little more quiet and peace. ideally things would get reviewed quicker and maintainers shouldn't be scared to merge things. these kitchen sinks especially are way too much to carry for just 3-4 devs.

threejs has a trust problem. it doesn't give stake, and it couldn't because addons is part of core. hence there are hundreds of prs waiting, bug fixes and such, new features take years to come through.

**Comment by krispya** [comment]
The moment Paul mentioned the contributor issue I realized having them in a monorepo would not work. Being able to control the pace and quantity of dev per repo is too important to the open collective mission.

What would be really helpful as a dev working on a major for both libraries is if the repos were set up the same. Trying to remember which one expects yarn or pnpm or uses turbo or husky, the command names, etc., is annoying and slows me down.

**Comment by itsdouges** [comment]
Great points Krispy. Alright so it looks like this RFC has had its due course, I think the repo tooling consistency is a good one though, at least for drei and r3f. Deserves one being raised!
