### ISSUE TITLE
In Nextjs 13+ modular build fails, modules not found...

### ISSUE THREAD

**Issue by Cybermage83** [pmndrs/drei#1317]
- `three` version: 150
- `@react-three/fiber` version:8.11.5
- `@react-three/drei` version: 9.56.27
- `node` version:18
- `npm` (or `yarn`) version: 8+

### Problem description:
Any attempt to use drei components in Next.js 13+ build fail to find modules in variety of them 

Result in Module not found* possible client/server build configuration, shared packages that are not meant to be mixed, like say fs/path, buffer or whatever it maybe

If not used and only fiber is used, no problem build goes through, Drei libarary should work also, but it does not - odd behavior

### Relevant code:

This will work, you do the same with **Box** component, it will fail to build.
```js  
<mesh>
            <boxGeometry args={[1, 1, 1]}>
              <meshBasicMaterial color={0xffffff} />
            </boxGeometry>
          </mesh>
```

**Comment by trebeljahr** [comment]
I think I might be running into the same issue... 
still working on a minimal repro, but currently, I get this error: 
![image](https://user-images.githubusercontent.com/25333032/223451634-7aec78ea-833e-40b5-b095-2581d4bda11e.png)

it happens when trying to use anything from the @react-three/drei package and I am at my wit's end as to *why* this might happen. The next.js setup I use is quite involved, however, r3f on its own doesn't break things, the above error only happens when trying to include anything from drei.
