### ISSUE TITLE
<Html /> with Scrollcontrols

### ISSUE THREAD

**Issue by Benjamin0203** [pmndrs/drei#1326]
- `three` version: ^0.148.0
- `@react-three/fiber` version: ^8.9.2
- `@react-three/drei` version: ^9.50.3
- `node` version: v16.18.1
- `npm` (or `yarn`) version: 8.19.2

### Problem description:

Hi I need some help with scrollcontrols. Whenever I scroll the laptop and Html  together, the Html always moves faster(it "jumps" out of the laptop when you scroll down) as you can see from here https://codesandbox.io/p/github/Benjamin0203/ReactThreeHelp/main?file=%2FREADME.md  is there a way to fix it so that they both move at the same pace?  here's my repo just incase the sandbox does not work: https://github.com/Benjamin0203/ReactThreeHelp thank you!

### Relevant code:

```js
let your = (code, tell) => `the ${story}`
```

**Comment by bryndsey** [comment]
This sounds similar to https://github.com/pmndrs/drei/issues/1048

There is a [workaround by specifying a portal for your Html component](https://github.com/pmndrs/drei/pull/1126#issuecomment-1410468830). However, I found that using the element originally described in the original comment was causing some annoying behavior with events (for example, you can no longer scroll the ScrollControl if your pointer is inside of the HTML content).

I found a slight modification to the original suggestion that got eventing to behave how I expected - you can see my suggestion [here](https://github.com/pmndrs/drei/pull/1126#issuecomment-1437130012). However, I'll note that I was seeing my version cause flickering/glitchy behavior specifically with Firefox, and I haven't been able to figure out a root cause yet.

[Link to a codesandbox showcasing my version of the workaround](https://codesandbox.io/s/happy-shockley-hmyfqn?file=/src/App.tsx)

**Comment by Benjamin0203** [comment]
Thank you @bryndsey  I used that method and it worked like a charm!
