### ISSUE TITLE
camera-controls functionality

### ISSUE THREAD

**Issue by chrysillo** [pmndrs/drei#1387]
Why doesn't the camera-controls implementation with drei support all the features of the normal camera-controls. Such as having access to all the events like rest and sleep, and access to the API when user controls are disabled? 
In this example I'm able to move the camera around while the user controls are disabled https://yomotsu.github.io/camera-controls/examples/orthographic.html

Is it recommended to use vanilla three.js instead of react-three-fiber in this case?

**Comment by Panda64** [comment]
I was curious about this as well. I've just been using the vanilla event listener for the other events, but it would be nice to have the others integrated if possible. Especially since `onStart` (`controlstart`) and `onEnd` (`controlend`) are not able to fire on mouse wheel control, leaving `control` to be the only user-specific event that does this.
