### ISSUE TITLE
AccumulativeShadows goes all black on iPad Safari

### ISSUE THREAD

**Issue by sngazm** [pmndrs/drei#1611]
- `three` version: 0.155.0
- `@react-three/fiber` version: 8.13.6
- `@react-three/drei` version: 9.80.3
- `node` version: 18.12.1
- `npm` (or `yarn`) version: 1.22.19

### Problem description:

On iPadOS Safari, where AccumulativeShadows is used, the entire plane slowly turns black instead of a shadow appearing on the plane.
All the examples in CodeSandbox have the same problem.

I confirmed this with Safari on my iPadOS 16.6, but I don't know if this is an iOS-wide issue as I don't now have an iPhone.

I have checked and it seems to go black regardless of the option values set, such as `alphaTest`, regardless of how large or small they are. As the value of `alpha` decreases, black planes also become transparent.

### Relevant code:

The following official samples where AccumulativeShadows is used have this problem. 

https://codesandbox.io/s/hxcc1x
![IMG_0003](https://github.com/pmndrs/drei/assets/4480229/3dc82e05-8ce7-4c27-b497-9c60d7d78d5d)

https://codesandbox.io/s/19uq2u
![IMG_0002](https://github.com/pmndrs/drei/assets/4480229/75ab7f7d-c217-42a9-a359-3d19f1a16c3c)

**Comment by hitmarten** [comment]
I got the same issue on my ipad (tried ios 16.6 and 17.0 beta) with safari. Edge(115) and chrome(115) do not have this issue.
Also tried this with my Iphone se(ios 16.6) but the shadows appear correct. So it doesn't seem to be ios-wide.

**Comment by hitmarten** [comment]
I think i found the issue and i will try to create a pr.

### Issue
The issue is in the following line:
```
const format = /(Android|iPad|iPhone|iPod)/g.test(navigator.userAgent) ? THREE.HalfFloatType : THREE.FloatType
```

When forcing THREE.HalfFloatType the shadows are rendered correctly.

So why does the user agent test fail?
By default safari displays the user agent as Macintosh instead of Ipad. Edge and Chrome don't do this.

Then why does `THREE.FloatType` not work. 
According to the THREE [documentation](https://threejs.org/docs/#api/en/textures/DataTexture). THREE.FloatType requires the 	OES_texture_float and OES_texture_float_linear extensions for some operation. My Ipad air 5 doesn't seen to have support for OES_texture_float_linear.

### Fix
We should check for webgl extensions instead of using the user agent.
Possible fix:

```
function checkFloatTextureSupport(renderer: THREE.WebGLRenderer): boolean {
  const gl = renderer.getContext()

  const floatTextureExtension = gl.getExtension('OES_texture_float')
  const floatLinearExtension = gl.getExtension('OES_texture_float_linear')

  if (floatTextureExtension && floatLinearExtension) {
    return true // Both extensions are supported
  } else {
    return false // One or both extensions are not supported
  }
}
```

**Comment by sngazm** [comment]
Thank you for the improvement!! It helps me a lot.
