### ISSUE TITLE
<Html> with <OrthographicCamera> disappears at certain orientations

### ISSUE THREAD

**Issue by anuragsr** [pmndrs/drei#179]
I am using the `OrthographicCamera` with `Html` from `@react-three/drei`
With this combination, the html `.content` divs seem to disappear intermittently.

I'm using `OrthographicCamera` with `Html` in a client project and faced this issue there first, so I forked the basic `Html` example and simply added an `OrthographicCamera` to the scene. The issue is seen there too. What could be the cause and how to fix it?

I did inspect the dom and find that a `display: none;` property is added to the `.content` div's parent but unsure what the condition is for adding that.

Here's the [codesandbox link](https://codesandbox.io/s/r3f-suspense-forked-ldwog?file=/src/index.js)

**Comment by giulioz** [comment]
That's because `display:none` is added if the object is behind the camera. If you look at the Html component implementation you'll see that it's using the camera position:
https://github.com/pmndrs/drei/blob/418a9ac0491e72cbfa1076cdd8d4ad483d216f66/src/Html.tsx#L21

In your example you have objects rendering behind the camera (since you have a negative near plane). To fix this you need to move the camera behind:
`<OrthographicCamera makeDefault position={[0, 0, 1000]} zoom={30} near={0} far={10000} />`

**Comment by anuragsr** [comment]
Ah thank you! Knew it was something related to camera pos..closing this.
