### ISSUE TITLE
Raycasting on `<Instances>` may be quadratic in number of instances

### ISSUE THREAD

**Issue by gewesp** [pmndrs/drei#1804]
- `three` version: Current
- `@react-three/fiber` version: current
- `@react-three/drei` version: current
- `node` version: not relevant
- `npm` (or `yarn`) version: not relevant

### Problem description:

I'm pretty sure that the indexOf() here makes raycasting on instanced meshes quadratic in the number of instances:
https://github.com/pmndrs/drei/blob/master/src/core/Instances.tsx#L73

### Relevant code:

https://github.com/pmndrs/drei/blob/master/src/core/Instances.tsx#L73

### Suggested solution:

Not 100% sure, but it seems that the only purpose of the search is to obtain the instanceId of the `PositionMesh` the raycast is being called on.  Maybe this can be just stored on the `PositionMesh` object instead.

**Comment by drcmda** [comment]
would you like to make a draft or pr with the proposed change?

**Comment by gewesp** [comment]
Yep, we could look into it.  Do you have an opinion on the proposal above (i.e. just storing the instanceId)?

**Comment by CodyJasonBennett** [comment]
One reason for storing its own group reference instead of an id is that the id is volatile when instances unmount. So, maybe we still store the id, but notify the parent when a component unmounts, and update those ids in a loop from a `useLayoutEffect`. React will batch state calls, and the layout effect ensures this happens before presentation.
