### ISSUE TITLE
View children no access to React Contexts

### ISSUE THREAD

**Issue by shalanah** [pmndrs/drei#1961]
### What is your question:

I'm having issues with child components of `View` accessing React Context. Any workarounds for this? 

I know I stumbled into a similar issue with the `Html` element once too but found a workaround here https://github.com/pmndrs/drei/issues/1137#issuecomment-1307474176 .

**Comment by shalanah** [comment]
I have a codesandbox with the issue: 
https://codesandbox.io/p/sandbox/view-context-rhk4j2?file=%2Fsrc%2FApp.tsx%3A8%2C11

Uncomment line 7 and useMainContext is still `null`.

**Comment by shalanah** [comment]
As a band-aid I'm able to directly wrap the children in a provider - works for my purposes but isn't as clean as the provider working properly and having all children have access.

**Comment by talkingtab** [comment]
If you wrap the Scene in the Context instead of the view it works 

https://codesandbox.io/p/sandbox/view-context-forked-v525x2

**Comment by jelling** [comment]
@shalanah were you able to fix this / would you mind showing our provider example?

What I learned from your `<Html>` link above helped me solved that issue. For anyone else running into that, the fix is to use `useContextBridge` from the `its-fine` library instead of the hook with the same name from drei. Example:

```
import { useContextBridge } from 'its-fine'; // different import
```

then

```
  const ContextBridge = useContextBridge();

  return (
      <Html>
        <ContextBridge>
          <ShotRenderButton />
        </ContextBridge>
      </Html>
)

```
