### ISSUE TITLE
Bounds Ignores Group Scale

### ISSUE THREAD

**Issue by AndrewJSchoen** [pmndrs/drei#2027]
- `three` version: `0.166.1`
- `@react-three/fiber` version: `8.16.8`
- `@react-three/drei` version: `9.108.3`
- `node` version: `v20.9.0`
- `npm` (or `yarn`) version: `9.8.1`

### Problem description:

When using the `Bounds` component, it incorrectly ignores scaling applied to group objects (and possibly others). This applies to especially to cases where the group is scaled by reference. This results in a mismatch from the expected bounds, based on what you see in the visual.  

<img width="486" alt="Screenshot 2024-07-11 at 11 41 15 AM" src="https://github.com/pmndrs/drei/assets/5341396/65e1d057-ffdb-49ae-a562-ef78f4cf8c3e">

### Relevant code:

https://codesandbox.io/p/devbox/bounds-gltf-y7g9xc
```

### Suggested solution:

Not sure, but it does seem like this is consistent regardless of whether the scale is applied via props (if dynamic), or whether they are applied to the Three object directly by ref in `useFrame`. I have also tried manually triggering the `fit` and `clip` functions some time after loading, but this doesn't seem to make a difference.

**Comment by drcmda** [comment]
it does seem to center the model correctly in the demo you made?
it seems to me you expect the component with the red wireframe to re-render because you called bounds.refresh().clip().fit()
but that call won't trigger any state updates, it merely refreshes internals and starts cam transforms
essentially bounds works, the component shows the old bounds because it doesn't re-render
