### ISSUE TITLE
(Next.js) Router + (Drei's) <Html> error

### ISSUE THREAD

**Issue by servinlp** [pmndrs/drei#215]
When trying to add either a `<Link>` tag or an element that onClick triggers a `router.push()` inside a `<Html>` tag both error with the following.
```
TypeError: router is null
```
A simple example of the code used is this:
```javascript
<Html>
  <p onClick={() => {
      router.push("/about");
   }}>hi</p>
</Html>
```
Here is a simple repo that reproduces the error: [Repo](https://github.com/servinlp/next.js-drie-html-error)

The interesting thing that i found is that if you put this piece of code directly bellow the `<Canvas>` element it works but as soon as you put it in a child component (what in my case is necessary) this error occurs.

Hopefully someone could help me out in a way that i can avoid `location.href = "/something"`.

**Comment by Pomevak** [comment]
I think it's because R3F is a different renderer, currently it does not share contexts with the default react renderer,  as is explained [here](https://github.com/servinlp/next.js-drie-html-error.git).

However, `next/router` has exported a singleton router. So you may do something like this to make it work

```javascript
import Router from "next/router";

...
         <p
            onClick={() => {
              Router.push("/about")
            }}
          >
            hi
          </p>
...
```

**Comment by servinlp** [comment]
Thanks that works. Closing issue.
