### ISSUE TITLE
Sky codesandbox/example is broken due to missing dependency

### ISSUE THREAD

**Issue by jure** [pmndrs/drei#305]
### Problem description:

The Sky codesandbox is broken: https://codesandbox.io/s/r3f-sky-3q4ev

```
DependencyNotFoundError
Could not find dependency: 'drei' relative to '/src/index.js'
```

### Suggested solution:

```js
import { Sky, TrackballControls } from '@react-three/drei'
```

I'd make a PR, but I can't find if there is an automated way to update these codesandboxes through commits.

**Comment by joshuaellis** [comment]
I think @gsimone knows about the sandbox examples?

**Comment by joshuaellis** [comment]
Hi @jure I've spoken with @gsimone and because this sandbox is externally managed (they're not built from our repo) they're impossible to manage.

Our course of action is to remove the links from the README, replace with a storybook entry & from there if any are missing create an issue containing a large storybook update.

**Comment by joshuaellis** [comment]
update: i've done the move in the README, didn't find anything in there that **had a sandbox but did not have a story**. However, there may be some components which do have a story, but i didn't link to, so lets keep an eye out 👀

**Comment by jure** [comment]
Thank you for looking into this Josh! Sounds good to me.
