### ISSUE TITLE
<Html> conflicts with Pointer events

### ISSUE THREAD

**Issue by geoff-harper** [pmndrs/drei#319]
I have a sphere mesh with an `onPointerOver` that reveals an `Html` info box and an `onPointerOut` that hides it, pretty straightforward. Unfortunately (and expectedly I guess) if you hover over where the info box visually obstructs the mesh, it produces flicker as it rapidly toggles visibility. 

What approach can I take to resolve this, if there are any? Ideally there would be a prop that behaves opposite of `center` but I can imagine there's some difficulty doing such a thing. Worst case I can regress to an on click to open and a close inside the box but I wanted to throw it out there in case I'm overlooking something

**Comment by geoff-harper** [comment]
Moments after posting this I woke up and put a `pointer-events: none` on the `<Html>` style prop and it resolved the issue. I'll leave it up for anyone else having trouble

**Comment by rvanlaarhoven** [comment]
Could it be that this is currently broken? Adding the `pointer-events: none` to the <Html> style prop has no effect, because the wrapping element does not receive those styles. Looking at the [Html](https://github.com/pmndrs/drei/blob/master/src/web/Html.tsx) source I also cannot find a way to alter the styles of the wrapping element. 

I see that when passing `transform={true}` the `pointer-events: none` is automatically being added. Shouldn't this also be the case for `transform={false}`? (See https://github.com/pmndrs/drei/blob/master/src/web/Html.tsx#L147)

**Comment by rvanlaarhoven** [comment]
I currently solved it by using a ref to find the parent to adjust its styles:

```JavaScript
const SomeComponent = () => {
  const ref = React.useRef()

  if (ref.current) {
    ref.current.parentElement.style.pointerEvents = 'none'
  }
  
  return <Html ref={ref} />
}
```

**Comment by verekia** [comment]
This is what works now:

`<Html style={{ pointerEvents: 'none' }}>`

**Comment by Jeremboo** [comment]
I'm on v9.88.15 and the solution proposed by @verekia doesn't worked for me. It still doesn't impact the correct wrapper.

I had to go with the @rvanlaarhoven solution with little adjustments: 

```typescript
const SomeComponent = () => {
  // useRef() can't be used here because the element is not returned the first time.
  const [htmlElement, setHtmlElement] = useState<HTMLDivElement | null>(null);
  useEffect(() => {
    if (htmlElement && htmlElement.parentElement) {
      htmlElement.parentElement.style.pointerEvents = 'none';
    }
  }, [htmlElement]);
  return <Html ref={setHtmlElement} />;
};
```

**Comment by alexsafayan** [comment]
There is a also deeper issue here. The pointer's position jumps to 0,0 when hovering an <Html> object

**Comment by dberardo-com** [comment]
i dont know if this the right place, but is it possible to prevent the element from inside the HTML element to propagate their drag mouse event ? i am struggling with this because basically i have an element inside the HTML wrapper that has a draggable handle.

if i drag the handle then the whole orbit controls will cause the 3d scene to move around. I managed to stop the onWheel event from propagating but cannot do that with the mouse drag
