### ISSUE TITLE
Sky with z=up

### ISSUE THREAD

**Issue by danvk** [pmndrs/drei#349]
### What is your question:

I'm using z=up in my scene, which I configure via the camera. This has been working great for me, except for the `<Sky/>` component:

```ts
<Canvas
  camera={{position: initCameraPosition, up: [0, 0, 1], near: 10, far: 10_000}}
  gl={{logarithmicDepthBuffer: true}}
  pixelRatio={window.devicePixelRatio}>
  {/* ... other elements ... */}
  <Sky distance={10_000} sunPosition={[0, 0, 10_000]} />
</Canvas>
```

This gives somewhat comical results:

![image](https://user-images.githubusercontent.com/98301/113063233-f6f59e00-9182-11eb-8103-98566c037af9.png)

Is it possible to tell the `Sky` which way is up?

**Comment by danvk** [comment]
(In case it's helpful to anyone else… I resolved this by changing the rest of my scene to use y=up)

**Comment by SoundRabbit** [comment]
This issue is already closed (and 3 years passed), but I just ran into the same issue and just solved it.

I found uniform `up` in original shader : https://github.com/pmndrs/three-stdlib/blob/main/src/objects/Sky.ts . Therefore, it resolved by adding `material-uniforms-up-value={[0, 0, 1]}` to the properties.

like this:
```ts
<Sky distance={10_000} sunPosition={[0, 0, 10_000]} material-uniforms-up-value={[0, 0, 1]} />
```
