### ISSUE TITLE
Should we support a <crowd/> component to optimise to render numerous geometry which share a same material?

### ISSUE THREAD

**Issue by slahser1992** [pmndrs/drei#430]
### Describe the feature you'd like:

optimise numerous geometries rendering by reducing drawcall.
 
### Suggested implementation:

I wanna merge many geometries to one by BufferGeometryUtils.megeBufferGeometries and render it just one time. like this:
```
<crowd mtl={[mtl1, mtl2, mtl3]}  mtlIndex={[3, 8]}>
    {
      [....].map(obj => <bufferGeometry {...obj}/>)
    }
<crowd/>  
```

**Comment by looeee** [comment]
I guess the new `Merged` component can be used for this? Although it doesn't merge the geometries with `mergeBufferGeometries` but rather instances them.

**Comment by joshuaellis** [comment]
@slahser1992 would `Merged` fulfil your requirements?

**Comment by drcmda** [comment]
i think merged would be perfect. and soon threejs will have batchedinstances, and then we can add another small helper. then we have

- Instances, one geom, one material, instanced and vertexcolors
- Points, one material, instanced and vertexcolors
- Merged, multiple geom, multiple material, instanced
- Batched, multiple geom, one material, instanced

**Comment by looeee** [comment]
> Instances, one geom, one material, instanced and vertexcolors

The way to get around the one material limitation is to add custom material uniforms using `material.onBeforeCompile` - see the [webgl_instancing_modified](https://threejs.org/examples/?q=modified#webgl_instancing_modified) example (it's modifying to add instance colors because the example dates before those were added by default). I wonder if there's a way to add a helper for this to drei?
