### ISSUE TITLE
Html component disappears when center is behind camera, but edges are on camera

### ISSUE THREAD

**Issue by jldinh** [pmndrs/drei#441]
- `three` version: 0.129.0
- `@react-three/fiber` version: 6.2.2
- `@react-three/drei` version: 5.2.2
- `node` version: 14.17.0
- `yarn` version: 1.22.5

### Problem description:

When the center of an Html component is behind the camera (in transform mode), it disappears. But the center being behind the camera does not necessarily mean none of it should be visible, when the camera is relatively close to the Html component.

### Relevant code:

https://codesandbox.io/s/musing-knuth-4tn5w?file=/src/index.js

In this example, a camera moves back and forth over an Html component (light blue with text). When it moves over the center, the component disappears and reveals a red Plane underneath.

### Suggested solution:

I saw the HTML div gets a `display: none` style if the following check returns true.

https://github.com/pmndrs/drei/blob/140d376c031589b6dd89855f164eb34fe76c63ef/src/web/Html.tsx#L21-L27

Is the check really necessary? I did not notice any adverse effect when disabling it.
If it is a performance optimization, I would suggest adding a prop to disable the check.

**Comment by looeee** [comment]
> Is the check really necessary? I did not notice any adverse effect when disabling it.

If you have just one or two Html components you probably won't notice any difference. But by the time you have hundreds it's vital. 

However I do agree that it should be possible to disable it for use cases like yours. 

Side note: In my own project I updated this to be `isObjectInFrustum` which gives even better results - the only problem is keeping the frustum in sync with the camera's frustum. It's expensive and needs to be done once rather than for every label.
