### ISSUE TITLE
AdaptiveDpr does nothing

### ISSUE THREAD

**Issue by yaroslavnikiforov** [pmndrs/drei#474]
- `three` version: 0.130.1
- `@react-three/fiber` version: 7.0.3
- `@react-three/drei` version: 7.0.6

### Problem description:

When you drop AdaptiveDpr into your scene you don't get any performance improvements. The frame rate doesn't change.

### Sandbox:
[https://codesandbox.io/s/volumetric-light-forked-ldld1?file=/src/index.js](https://codesandbox.io/s/volumetric-light-forked-ldld1?file=/src/index.js)

**Comment by joshuaellis** [comment]
@drcmda would you mind looking at this when you get time please? 🙏🏼

**Comment by drcmda** [comment]
your model just moves, it would make no sense to use adaptivedpr here because if you never get still-stand you can outright give it a lower resolution if you so desire using canvas dpr={...}. the feature is made for temporarily moving scenes, where it can less impact and ramp up on still stand again. look into this: https://twitter.com/0xca0a/status/1407371461447368705 it explains the process.
