### ISSUE TITLE
Rendering Html-Element breaks app with "missing react-dom" error although react-dom is installed

### ISSUE THREAD

**Issue by DoctypeRosenthal** [pmndrs/drei#557]
- `three` version: 0.132.2
- `@react-three/fiber` version: 7.0.7
- `@react-three/drei` version: 7.8.0
- `node` version: 16.9.1
- `npm` (or `yarn`) version: 7.21.1

### Problem description:

See https://github.com/pmndrs/drei/commit/4fd9cf191054b7fb0220e7a73d2276f74b8520ea#commitcomment-56962016.

**Comment by saitonakamura** [comment]
@DoctypeRosenthal what's snowpack way to define a runtime import? When I was implementing this I just assumed most of the bundlers are properly supporting `require` calls, but apparently it's not the case. As for the 

> Make 'react-dom' a non-optional peerDependency again as in "drei" v7.6.0.

In theory it was already an optional peerDependency (if you look at package.json) on 7.6.0 and before, it's just weren't so in practice. In #521 only import way has been changed
If we can support such dynamic import for most of the bundlers I'd be happy to implement

**Comment by DoctypeRosenthal** [comment]
What is the reasoning behind an optional dependency of react-dom?

**Comment by saitonakamura** [comment]
react-three-fiber can be easily used without react-dom (if you don't need it), allows to strip a lot of bytes. https://docs.pmnd.rs/react-three-fiber/API/render-function

**Comment by drcmda** [comment]
> react-three-fiber can be easily used without react-dom (if you don't need it), allows to strip a lot of bytes. https://docs.pmnd.rs/react-three-fiber/API/render-function

though, having the dependency does not hurt. if you don't use Html it should never be part of the end bundle even though you have to have it in the dev environment. maybe we should revert the change if it causes that much trouble.

**Comment by saitonakamura** [comment]
Maybe. My original PR idea came when someone on discord couldn't understand why his application fails with "react-dom not found" despite them haven't been using it or Html component (the anwser were to use the import from `/native` directory which is hella confusing if you ask me).

The question is what current popular bundlers does not support this technique and whether it's easy to fix them (find a universal way to do so) or not. webpack and parcel are fine with this technique, snowpack obviously not, I haven't tried esbuild/vite or rollup

**Comment by drcmda** [comment]
i think bundlers in general are in a shakeup phase, so all bets are off.

**Comment by DoctypeRosenthal** [comment]
I wonder under which circumstances one would use react without react-dom. The two belong to each other like Doritos and Mountain Dew.

**Comment by joshuaellis** [comment]
I don't think we want to be publishing submodules because that would add to the complexity of the namespace and publishing of the modules.

I think the change @saitonakamura made was a welcome one and as long as we can find a solution for the bundler issue I don't have a problem with keeping it. If we can't though, we should revert it and people will have to deal with the imports the way they had for the past year previous when we originally made the move to make `react-dom` a peer dep.

**Comment by DoctypeRosenthal** [comment]
Rename it to something like @react-three/html. Then you would not only have the benefit of it being a separately installable module but also a more expressive package name, don't you agree?

**Comment by joshuaellis** [comment]
>Rename it to something like @react-three/html. Then you would not only have the benefit of it being a separately installable module but also a more expressive package name, don't you agree?

No I don't agree. The package as an entity would become harder to manage and deploy if we take that route.

>Or make react-dom non-optional. Is there any use-case where one would use react+threejs outside of a browser env?

There is, you can use r3f without `react-dom` as well. Previously it was run-able on `react-native`.

> If so, this import strategy above isn't the right choice either as it couples the code to a specific browser renderer (react-dom) where it should be using an Adapter instead.

If you think you can improve the method we have now of enabling users to import from the root i.e `@react-three/drei` as opposed to the long import then please do make a PR and it'd be helpful to see it. @saitonakamura like most of us, didn't realise that things like snowpack don't implement things like `require`, but the original change reduced the amount of questions about why it would break an individual's project.

**Comment by DoctypeRosenthal** [comment]
To be quite frank, this is bad software design: an "optional" dependency which is not optional and fails silently if the it isn't met, except for snowpack where our complete app breaks.
Since you don't want to split the web module into it's own package my only recommended solution is to make react-dom non-optional as a peer dependency for the drei package. Every modern bundler will treeshake it away if not used, as @drcmda mentioned.

**Comment by drcmda** [comment]
i would also lean into a revert tbh. the require stuff is a little hacky after all and if it messes with bundlers it's probably not worth the trouble. react-dom as a peer is not too much too ask, people will have to add it but it never ever goes into the bundle, well, unless Html is being used.

**Comment by joshuaellis** [comment]
>react-dom as a peer is not too much too ask and has no downsides

It is already a peer. The proposal to make it required, which previously people didn't want either if they were working on non browser platforms. See:
* https://github.com/pmndrs/drei/issues/221
* https://github.com/pmndrs/drei/issues/19#issuecomment-733558823
* https://github.com/pmndrs/drei/issues/212
* https://github.com/pmndrs/drei/issues/182

All these are around when react-dom was a required peer dep.

**Comment by DoctypeRosenthal** [comment]
@joshuaellis ok then I'd say that this module belongs into it's own package because it couples tightly with react-dom and is not usable in a react-native environment.

**Comment by saitonakamura** [comment]
Btw, I asked one guy who knows a lot about bundlers on twitter and he basically said "just use different entrypoints" (https://twitter.com/IAmTrySound/status/1442412936073523200)
Which drei already uses (web and native), it's just the web is a default one, and having to use `/native` (and for all imports no less) because I don't have `react-dom` is pretty confusing IMO

If we can consider a breaking change for Html component I have two proposals

1. Move Html component from the web https://github.com/pmndrs/drei/blob/master/src/web/index.ts#L1, and require to use a different import for it, say `import { Html } from '@react-three/drei/Html'` (we can bikeshed later). `import { Html } from '@react-three/drei'` will no longer be possible. That way Html won't be imported when you import anything else but it
2. Inject `ReactDOM.render` and `ReactDOM.unmountComponentAtNode` (or the whole `ReactDOM`) as props to Html component. That way Html won't need an internal import and importing react dom will be done by the userland

I like neither of them, but considering won't hurt I guess

**Comment by joshuaellis** [comment]
> yes, but all of these would have been resolved by pulling from drei/native, correct?

They were, which is why it is is how it is now 😄 we have `web` and `native` and `/` is an alias for `web` since _most_ people use `three` in a web env.

**Comment by drcmda** [comment]
but it would still be unnecessary, now the 99.9% will come here and complain because their go-to usecase doesnt work no more, there are thousands of apps out there just using drei, and we'll break them all. there are maybe 10 people using the render function on the other side. and i think /, /web, /native is explicit because you know if your app uses react-dom or not. whereas having to double check if this or that feature internally uses it is kind of odd.

it's imo just a docs issue. the readme in general could benefit from a do-over.

**Comment by joshuaellis** [comment]
Well we're in agreement that we don't need to do anything to the repo but remove the inline require because it crashes applications.

**Comment by drcmda** [comment]
then i'd propose we do it (the revert) and we could start collecting ideas how to make the docs more accessible. maybe we should have clear flags, or we split categories into generic/native and web. i would also like to have a more dense layout but i suppose markdown grids are too limited? can grid cells even contain code blocks?

**Comment by drcmda** [comment]
using the wiki perhaps? i've never used it, but would it make sense to put deeper feature explanations in there?

**Comment by joshuaellis** [comment]
In the interest of moving forward, i'm reverting the change to silently fail `Html` and we can open a new issue in the interest of improving our documentation 😄

**Comment by joshuaellis** [comment]
this was closed with f6ad92a
