### ISSUE TITLE
Can't get Merged to work with a Blender gltf

### ISSUE THREAD

**Issue by oallouch** [pmndrs/drei#610]
- `three` version: 0.134.0
- `@react-three/fiber` version: 7.0.17
- `@react-three/drei` version: 7.19.2
- `node` version:
- `npm` (or `yarn`) version:

### Problem description:
I tried to reproduce my problem with the simplest gtb exported from Blender.
I only get "Cannot read properties of null (reading 'id')"

### Relevant code:
https://codesandbox.io/s/merged-test-kphj6?file=/src/App.js

Btw, having a Merged example in the storybook would be great.

Thx in advance

**Comment by drcmda** [comment]
```jsx
 const { nodes } = useGLTF('/testMerged.glb')
 const meshes = { Icosphere: nodes.Icosphere }
  return (
    <Merged meshes={meshes}>
```

here's a complex examples, gltfjsx auto-generates these for you: https://codesandbox.io/s/merged-instance-kud9p?file=/src/Model.js

the crash happens because the scene is part of `nodes`. but i think nodes was supposed to only have meshes, currrently it is a flat collection of all objects, groups and otherwise. merged expects meshes only. i added a filter to Merged, it's up in a few minutes.

**Comment by oallouch** [comment]
I updated the drei version, but I still got an error, this time the infamous "Element type is invalid: expected a string..."
Btw, I don't see the scene in "nodes".
Maybe you should add an example in the storybook with the second part of https://github.com/pmndrs/drei#merged (the gltf one).

**Comment by drcmda** [comment]
oh no :-S i can never remember remember if array.filter is positive or negative. accidentally filtered out every mesh instead of non-meshes. should be fine finally in a few minutes.

**Comment by oallouch** [comment]
ah ah :)

**Comment by drcmda** [comment]
looks like the build queue got stuck. here's your working box https://codesandbox.io/s/merged-test-forked-1yz9t

**Comment by oallouch** [comment]
nice !

thx so much
