### ISSUE TITLE
three.js >= 0.137 will break example import

### ISSUE THREAD

**Issue by floofy-moo** [pmndrs/drei#747]
- `three` version: >= 0.137
- `@react-three/fiber` version: ^8.0.0-beta-05
- `@react-three/drei` version: 9.0.0-beta.1
- `node` version: v16.13.0
- `npm` (or `yarn`) version:8.1.0

### Problem description:

Using the `three` version listed above will result in errors importing `stats.min.js` in `node_modules/@react-three/drei/core/Stats.js`:

```
Package path ./examples/js/libs/stats.min is not exported from package /Users/[redacted]/node_modules/three (see exports field in /Users/[redacted]/node_modules/three/package.json)
```

Upon checking the `exports` field mentioned above, it seems like it only includes the `jsm` examples, not `js`. This field seems to have been added in 0.137. 

See this commit: https://github.com/mrdoob/three.js/commit/1c685e6eb56e54c4609b7b3af764e2e5110abfbf#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R8

### Suggested solution:

* (for users of drei) Use older version as a work around
* (for developer of drei) the following are guesses
  * Try using jsm version
  * Ask developer of three to include js version in exports

**Comment by looeee** [comment]
Stats.js should probably be imported from here rather than from three.js

https://www.npmjs.com/package/stats.js

**Comment by ChrisCrossCrash** [comment]
I was also getting the `stats.min is not exported` error. I never even imported `Stats`. I was just importing `Box` from Drei into a `.tsx` file. Updating my dependencies fixed the issue.

I was having the error with these versions:

```javascript
"@react-three/drei": "8.6.3",
"@react-three/fiber": "7.0.25",
"@types/three": "0.137.0",
"three": "0.137.5",
```

But then it worked after updating to the following:

```javascript
"@react-three/drei": "8.11.0",
"@react-three/fiber": "7.0.26",
"@types/three": "0.137.0",  // same
"three": "0.137.5", // same
```

@subachev-bonematch I realize you are using beta versions. Perhaps you need them or you are just testing them, but have you tried using the latest non-beta versions?

**Comment by skrat** [comment]
Yepp, same issue here.

**Comment by skrat** [comment]
Ok, so 1st thing: workaround - just don't import stuff from barrel files, import what you need from the package, eg. `import { useGLTF } from '@react-three/drei/core/useGLTF';` this will remove the stats.js error and it will optimize your build, make it easier to tree-shake.

But, and this is a big one for @pmndrs I was battling some weird `ShadowMaterial` issue

![image](https://media1.giphy.com/media/tqHpynwh4L0oAu8D1A/giphy.gif?cid=790b761107cd28f8424d2624392e5e7cea2a8f7b12ab8eb9&rid=giphy.gif&ct=g)

And it made me upgrade to latest `three`, and `@react-three/{fiber,drei}` versions. That's how I got the stats.js error. So I applied my workaround, importing from withing the package instead of the barrel file, and voila! My shadow plane issues are gone.

So to conclude, I don't what you guys are doing, and I love your libraries, but this smells from some side effecting into three.js and that sure is no good.
