### ISSUE TITLE
GizmoHelper shows "Back" on all sides

### ISSUE THREAD

**Issue by natarius** [pmndrs/drei#791]
- `three` version: 0.138.3
- `@react-three/fiber` version: 8.0.0 beta 05
- `@react-three/drei` version: 9.0.0 beta 1
- `node` version: NA
- `npm` (or `yarn`) version: NA

### Problem description:

<img width="438" alt="Screen Shot 2022-03-08 at 10 50 16 AM" src="https://user-images.githubusercontent.com/607331/157305278-b234a33b-ec0c-4703-813a-b9df5c42db64.png">

The Gizmo Helper shows "Back" on all its sides

### Relevant code:

(https://codesandbox.io/s/floating-instanced-shoes-forked-jtbwpk?file=/src/App.js)

**Comment by susiwen8** [comment]
I’m interested in this issue. Can I take this?

**Comment by gsimone** [comment]
@susiwen8 sure, hop on the discord if you need help contributing or just shoot me a DM or a mention here

**Comment by susiwen8** [comment]
I can assure that this is R3F v8 problem. `attach` logic has been refactored
https://github.com/pmndrs/react-three-fiber/commit/f4a0ecc0ed189a695aeca9006d7a134e36b2664a
It affects `MultiMaterial`, cause `attachArray` has "accidentally" left out. I don't know it was intentional or what
Looks like this commit want to group `attach` to one function. I'm gonna make a PR for it, maybe @drcmda @gsimone can review it and give me a pointer

**Comment by susiwen8** [comment]
M'y mistake, it appears drei beta bug

**Comment by susiwen8** [comment]
Could we close this issue now?
