### ISSUE TITLE
Stage not centered anymore

### ISSUE THREAD

**Issue by pelikhan** [pmndrs/drei#949]
### Problem description:

It seems that Stage does not center the view (vertically) on the center of the module any. This can be demonstrated on the Stage storybook where the view is centered on the bottom of the sphere.

https://drei.pmnd.rs/?path=/story/staging-stage--stage-st

![image](https://user-images.githubusercontent.com/4175913/173427833-01be28d1-c5c8-4c5e-98f1-ef3bf4567004.png)

**Comment by Cecile-Lebleu** [comment]
I'm having the same problem. Adding two axesHelpers, one right outside and one inside Stage, gives two different positions. The position of axesHelper inside Stage changes when other objects are added to Stage.
![Screen Shot 2022-07-07 at 6 06 09 PM](https://user-images.githubusercontent.com/22694361/177891077-5ed4273d-d144-4d1a-88fb-c484801af9a6.png)

This is making it very hard to use QuadraticBezierLine, since the end is offset by Stage's position offset. Here the line should go from [0,0,0] to the cube's position at [1,1,1]; but it seems like the positions are almost random. I'm trying to make up for that offset manually but it feels hacky and wrong.
![Screen Shot 2022-07-07 at 6 11 30 PM](https://user-images.githubusercontent.com/22694361/177891426-045caca5-64e4-4719-8eae-8abcb2818938.png)

Any updates on this?

**Comment by drcmda** [comment]
that's odd, could someone look through the change history for that component or go a few versions back until it works so that we can isolate it. i've no time unfortunately. :-(

**Comment by Cecile-Lebleu** [comment]
[Here's a very simple sandbox](https://codesandbox.io/s/silly-franklin-4h8bn4?file=/src/App.js) with two axesHelpers: one inside and one outside Stage. That's it.

It almost seems like it might have been like this since the beginning. I was able to go back to **drei v4.3.0 and still replicate the problem.** Couldn't go earlier because [errors](https://stackoverflow.com/a/57115099), react versions, naming conventions, dependencies and versions 😵 which I honestly don't know how to work around.

**Comment by FarazzShaikh** [comment]
@drcmda wasn’t this fixed recently?

**Comment by drcmda** [comment]
the center component was fixed, but stage isn't using that. it's using the broken logic that was fixed. with the tools that we have today i don't think stage should screen-center but just place the model on top of the screen-center-line where the shadow catcher is. if it should be screen center it should be wrapped into `<Bounds>`. but that's not how it's working currently.
